### ISSUE TITLE
Spark YARN Mode: Executors Showing Container ID Instead of Hostname & Unexpected Executor Shutdowns

### ISSUE THREAD

**Issue by nallaperumaletl** [cmdviegas/docker-hadoop-cluster#8]
Hi @cmdviegas @eduardo-correa First, thanks for your awesome work on this project — it’s been incredibly helpful! 🙏

I’m running the cluster in YARN mode, and I’d like to run multiple Spark worker containers with custom container_name and hostname, such as:

```python
spark-worker-1
spark-worker-2
```

![Image](https://github.com/user-attachments/assets/03129827-484d-4cfe-a17a-5e2f469859d7)

In the Spark UI under executors, I see entries like:
Executor ID | Address
------------|--------------------------
1           | 2831be42e1de:39987

Instead of:
Executor ID | Address
------------|--------------------------
1           | spark-worker-1:39987

This makes it hard to understand the distribution of tasks across containers, especially when debugging or monitoring performance. It would be really helpful if we could have Spark show the actual hostname or container name, like spark-worker-1, spark-worker-2, etc.

I understand SPARK_LOCAL_HOSTNAME can be used in standalone mode, but I’m running in YARN mode, and this doesn’t seem to apply. Is there a YARN-compatible way to reflect proper hostnames in the Spark UI?

2. ❌ Executors Randomly Go Dead While Spark Session Is Active
I've also noticed that some executors go into a "Dead" state even though the Spark session is still running. This causes intermittent issues or slows down processing.

In the Spark UI I see lines like:
Executor ID | Status
------------|--------
1           | Dead
2           | Dead
...

Could this be related to Spark worker timeout, container resource exhaustion, or Docker's restart policy?

Any guidance or best practices to keep Spark executors alive throughout the session would be hugely appreciated.

Happy to test changes and Thanks again for the awesome work and for your time!

**Comment by cmdviegas** [comment]
Dear @nallaperumaletl,

Regarding the hostname of worker nodes, this is a known issue since they are deployed in replicated mode. In this mode we can't set a hostname manually. In order to solve this, you can deploy each worker as a separated service instead of using replicated mode. So, you can achieve this by editing docker-compose file and adding something like this:

```
  worker-1:
    <<: *common
    container_name: ${STACK_NAME}-worker-1
    hostname: ${STACK_NAME}-worker-1
    volumes:
      - ./myfiles:/home/${MY_USERNAME}/myfiles
      - .env:/home/${MY_USERNAME}/.env
    command: ["WORKER"]

  worker-2:
    <<: *common
    container_name: ${STACK_NAME}-worker-2
    hostname: ${STACK_NAME}-worker-2
    volumes:
      - ./myfiles:/home/${MY_USERNAME}/myfiles
      - .env:/home/${MY_USERNAME}/.env
    command: ["WORKER"]

  worker-3:
    <<: *common
    container_name: ${STACK_NAME}-worker-3
    hostname: ${STACK_NAME}-worker-3
    volumes:
      - ./myfiles:/home/${MY_USERNAME}/myfiles
      - .env:/home/${MY_USERNAME}/.env
    command: ["WORKER"]
```

... and so on. If you experience some erros after changing hostnames, I advise you to restart the cluster from scratch (I mean, remove all containers and volumes associated and then create them).

Regarding the working nodes going dead, it is hard to diagnose without checking the error logs. Inside each container, you can inspect the logs to look for clues:

```
/home/myuser/spark/logs
/home/myuser/hadoop/logs
```

In my opinion, there is nothing related to docker restart policy. It's more likely caused by the task itself — maybe a missing dependency or a logic error. But you need to check this.
